### ISSUE TITLE
Migrate shell scripts to ansible where possible

### ISSUE THREAD

**Issue by reavon** [NLM-OCCS/occs-packer#1]
1. Migrate the current shell provisioning scripts into Ansible roles.
2. Remove puppet place-holder provisioner.

Once this is complete, we should have Ansible role(s) that do the initial customization of the image.

**Comment by danizen** [comment]
Sounds like you want Ravi and I to hold off until you've completed this, and to do our specific customizations for Java/Tomcat, Ruby, Python, Node as roles.   Is that correct?

**Comment by reavon** [comment]
I would go ahead and do your customizations. This is my nagging reminder for what I want to do long term.

**Comment by reavon** [comment]
I am going to use this https://github.com/RedHatGov/ansible-role-800-53 to replace the bash scripts (https://github.com/NLM-OCCS/occs-packer/blob/master/scripts/scripts_sysops/scap-fixes.sh) that are being used now. This will be much easier to maintain I think.
