### ISSUE TITLE
Rebuild issue

### ISSUE THREAD

**Issue by danizen** [NLM-OCCS/occs-packer#12]
Inconvenient to rebuild, because the outputs_directory already exists.   Not bad enough to change it myself.

**Comment by reavon** [comment]
I agree. I guess we could append the date to the ouputs. We could also just remove the contents of the build directory every time the script is ran. I am not wedded to either idea, but I do agree it is a hassle.

Thoughts?

**Comment by danizen** [comment]
Up to you - that's why I added `help wanted` ;)
